version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: festive_swirles
    restart: always
    environment:
      POSTGRES_DB: DbGerenciamentoDePessoas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GerenciamentoDePessoas
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=DbGerenciamentoDePessoas;Username=postgres;Password=1234
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge