services:
  db:
    image: postgres:latest
    container_name: dbgerenciamento_pessoas
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciamento_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__ConexaoPadrao=${DB_CONNECTION_STRING}
    networks:
      - app-network

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on:
      - db
    environment:
      - ConnectionStrings__ConexaoPadrao=${DB_CONNECTION_STRING}
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge